apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-3r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-3r
  template:
    metadata:
      labels:
        app: backend-3r
    spec:
      containers:
      - name: backend-3r
        image: tinnaung/backend-3r-chippichat:latest
        ports:
        - containerPort: 5789
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://mongo.svc.cluster.local:27017/sds-3r"
        - name: JWT_SECRET
          value: "chippichippichappachappa"
        - name: JWT_EXPIRE
          value: "30d"
        - name: JWT_COOKIE_EXPIRE
          value: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-3r
spec:
  ports:
  - port: 5789
    targetPort: 5789
  selector:
    app: backend-3r